#!/bin/sh

# should already be correct but let's make sure
chown -R root:admin "/Library/Printers/Xerox"
chmod -R go-w "/Library/Printers/Xerox"

if [ ! -d "/Library/Caches/Xerox" ]; then
	/bin/mkdir "/Library/Caches/Xerox"
fi

chmod 0777 "/Library/Caches/Xerox"

if [ -f /Library/Caches/ppdmgr ]; then
	/Library/Caches/ppdmgr -u -P "/Library/Printers/PPDs/Contents/Resources"
	rm -rdf "/Library/Caches/ppdmgr"
fi

# should already be correct but let's make sure
chown -R root:wheel "/Library/Printers/PPDs"
chmod -R go-w "/Library/Printers/PPDs"

# xsubinaries
cd /Applications/Xerox/Xerox\ Scan\ Utility/
for file in *.xst
	do
	if [ -f ${file} ];
	then 
	   mv -f "${file}" /Library/Caches/Xerox/"${file}"
	fi
done

# xsucontents and 107xsucontents
if [ -d /Applications/Xerox/Xerox\ Scan\ Utility/UpgradeXScanUtility.app ]; then
	exec /Applications/Xerox/Xerox\ Scan\ Utility/UpgradeXScanUtility.app/Contents/MacOS/UpgradeXScanUtility "/Library/Caches/Xerox/XSU.plist"  
fi

sleep 10

# PaperCut Client
# Fix executable 
find '/Applications/PCClient.app' -exec chmod 775 {} \\;
rm -fr ~/Library/Preferences/PCClient 2>/dev/null
export PC_CLIENT_ARGS=-a; open -a /Applications/PCClient.app/Contents/MacOS/JavaAppLauncher --args biz.papercut.pcng.client.uit.UserClient
echo "Launched JavaAppLauncher for confirm identitiy mode"

# Grab pre-existing printers
BW=$(lpstat -v | grep -i husky-bw | awk 'BEGIN { FS = "/" } ; NR==1{ print $NF}')
Color=$(lpstat -v | grep -i Husky-Color | awk 'BEGIN { FS = "/" } ; NR==1{ print $NF}')

# Remove BW and Color if they exist already
if [ -z $BW ]; then 
    echo "Deleting old $BW"
    lpadmin -x $BW
fi

if [ -z $Color ]; then 
    echo "Deleting old $Color"
    lpadmin -x $Color
fi

# Add new Color and BW with the adjusted drivers
lpadmin -p "Husky-Color" -E -v lpd://print.mtu.edu/husky-color -P /Library/Printers/PPDs/Contents/Resources/Xerox\ AltaLink\ C8055.gz -o XRTrays='SixTraysHCFTT' -o XRHolePunch='23Unit' -o XRFinisher='SBFinisher' -o printer-is-shared=false
lpadmin -p "Husky-BW" -E -v lpd://print.mtu.edu/husky-bw -P /Library/Printers/PPDs/Contents/Resources/Xerox\ AltaLink\ B8055.gz -o XRTrays='SixTraysHCFTT' -o XRFinisher='OF' -o XRHolePunch='TruePunch' -o printer-is-shared=false

# Grab the names again to be sure that they were added correctly
BW=$(lpstat -v | grep -i husky-bw | awk 'BEGIN { FS = "/" } ; NR==1{ print $NF}')
Color=$(lpstat -v | grep -i Husky-Color | awk 'BEGIN { FS = "/" } ; NR==1{ print $NF}')


if [[ $BW == "husky-bw" && $Color == "husky-color" ]]; then
  exit 0		## Success
fi
exit 1       ## Failure
