#!/bin/sh
## postinstall

pathToScript=$0
pathToPackage=$1
targetLocation=$2
targetVolume=$3

installer -pkg /private/var/tmp/huskyprint_mac/PCClient_19.2.3.53767.pkg -target $3
installer -pkg /private/var/tmp/huskyprint_mac/Xerox_Print_Driver_5.6.0.pkg -target $3

# Remove any old versions of the husky printers
lpstat -p | awk '{print $2}' | while read printer; do
    if [[ "$printer" == "husky"* ]]; then
        echo "Deleting printer: $printer"
        lpadmin -x $printer
    else if [[ "$printer" == "Husky"* ]]; then
        echo "Deleting printer: $printer"
        lpadmin -x $printer
    fi
    fi
done

# Add husky printers with drivers
# Currently we are using Xerox AltaLink B/C8055

# Husky-BW
echo "Adding Husky-BW"
lpadmin -p "Husky-BW" -D "Husky-BW" -L "Husky-BW" -E -v "lpd://print.mtu.edu/husky-bw" -P "/Library/Printers/PPDs/Contents/Resources/Xerox AltaLink B8055.gz"\
    -o printer-is-shared=false -o XRTrays='SixTraysHCFTT' -o XRHolePunch='TruePunch' -o XRFinisher='OFBM'

# Husky-Color
echo "Adding Husky-Color"
lpadmin -p "Husky-Color" -D "Husky-Color" -L "Husky-Color" -E -v "lpd://print.mtu.edu/husky-color" -P "/Library/Printers/PPDs/Contents/Resources/Xerox AltaLink C8055.gz"\
    -o printer-is-shared=false -o XRHolePunch='23Unit' -o XRFinisher='SBBookletFinisher'

rm -rf /private/var/tmp/huskyprint_mac/

exit 0