#!/bin/sh
## postinstall

pathToScript=$0
pathToPackage=$1
targetLocation=$2
targetVolume=$3

# install papercut
# Fix executable 
find '/Applications/PCClient.app' -exec chmod 775 {} \\;
rm -fr ~/Library/Preferences/PCClient 2>/dev/null
export PC_CLIENT_ARGS=-a; open -a /Applications/PCClient.app/Contents/MacOS/JavaAppLauncher --args biz.papercut.pcng.client.uit.UserClient

# Xerox printer drivers
installer -target $targetVolume -pkg /tmp/Xerox-Printers-4.22.2.pkg
rm -rf /tmp/Xerox*
rm -rf /Applications/Xerox\ PowerENGAGE.app
rm -rf /Applications/XeroxPEInstallationCompanion.app

# add husky prints
# Remove any old versions of the husky printers
lpstat -p | awk '{print $2}' | while read printer; do
    if [[ "$printer" == "husky"* ]]; then
        echo "Deleting printer: $printer"
        lpadmin -x $printer
    else if [[ "$printer" == "Husky"* ]]; then
        echo "Deleting printer: $printer"
        lpadmin -x $printer
    fi
    fi
done

# Add husky printers with drivers
# Currently we are using Xerox AltaLink B/C8055

# Husky-BW
echo "Adding Husky-BW"
lpadmin -p "Husky-BW" -D "Husky-BW" -L "Husky-BW" -E -v "lpd://print.mtu.edu/husky-bw" -P "/Library/Printers/PPDs/Contents/Resources/Xerox AltaLink B8055.gz"\
    -o printer-is-shared=false -o XRTrays='SixTraysHCFTT' -o XRHolePunch='TruePunch' -o XRFinisher='OFBM'
cupsenable Husky-BW

# Husky-Color
echo "Adding Husky-Color"
lpadmin -p "Husky-Color" -D "Husky-Color" -L "Husky-Color" -E -v "lpd://print.mtu.edu/husky-color" -P "/Library/Printers/PPDs/Contents/Resources/Xerox AltaLink C8055.gz"\
    -o printer-is-shared=false -o XRHolePunch='23Unit' -o XRFinisher='SBBookletFinisher'
cupsenable Husky-Color


exit 0
