#!/bin/sh
## preinstall

pathToScript=$0
pathToPackage=$1
targetLocation=$2
targetVolume=$3

# kill off any papercut client that already exists
pid=$(ps -A | grep -m1 PCClient.app | awk '{ print $1 }')
kill $pid

rm -rf $targetVolume/Applications/PCClient/
rm -rf $targetVolume/AppLications/PCClient.app


exit 0